model_name: "models/llm/Llama-3.2-11B-Vision-Surgical-CholecT50/"
#model_name: "models/llm/Qwen2.5-VL-7B-Surgical-CholecT50"
served_model_name: "surgical-vlm"
llm_url: "http://127.0.0.1:8000/v1"
personnel:
  surgeon: "Dr. Alice"
  assistant: "Mr. Scrub Tech"
  anaesthetist: "Dr. Bob"
